export const movies=[
    { id:1,
        title:"IRON MAN!",
    plot:"Iam Iron Man",
    price:250,
    rating:8.9,
    stars:0,
    fav:false,
    cart:false,},
    {
        id:2,
        title:"HULK BOY",
plot:"Iam Always Angry",
price:200,
rating:9,
stars:0,
fav:false,
cart:false,
    },
    {
        id:3,
        title:"THOR",
plot:"LIghting King",
price:200,
rating:9.5,
stars:0,
fav:false,
cart:false,
    },
    {
        id:4,
        title:"Captain America",
plot:"iam the captain",
price:200,
rating:9.5,
stars:0,
fav:false,
cart:false,
    },
    {
        id:5,
        title:"Black Panther",
plot:" Wakanda forever",
price:220,
rating:8.9,
stars:0,
fav:false,
cart:false,
    }

]